### ISSUE TITLE
“unwelcome physical force against people or property‘

### ISSUE THREAD

**Issue by dazzaji** [CoMakery/comakery-server#1658]
What does “unwelcome physical force against people or property“ mean?  It’s prohibited by the license but I’m not sure what exactly would be covered or not covered. It reminds me of “[battery](https://www.law.cornell.edu/wex/battery)” except it includes all “physical force” (seems very broad if interpreted literally) and it also applies to property. Is this intended to mean violent crimes or torts? More or other? When is application of force to property unwelcome - like if I touch a building while passing on the sidewalk and the owner doesn’t actively welcome the light application of force but neither are they against it, would that be a violation of the license?

**Comment by aquabu** [comment]
Thanks for the great questions @dazzaji

_For those following along keep in mind I'm not a lawyer, this is not legal advice. This is an informal discussion that doesn't represent my ongoing or definitive interpretation of the license as CEO of CoMakery. That said in the spirt of legal hacking for public good, I think public discussion to develop ethical source legal licenses is really important._

## Context

The nonviolent part of the [Noncommercial Nonviolent Public License](https://github.com/CoMakery/comakery-server/blob/40eddf95292a7463446721c29ef41baabd38f417/LICENSE.md) consists of mainly these two phrases:

> **Purpose**
> **This license allows you to use and share this software for noncommercial nonviolent purposes for free and to try this software for commercial nonviolent purposes for thirty days.**

> **Prohibited Purpose**
> **You may not use the software to promote, further, or assist the use of unwelcome physical force against people or property.**

## What does “unwelcome physical force against people or property“ mean?

The language is similar to the definition of "violence" in [18 U.S. Code § 16 (a)](https://www.law.cornell.edu/uscode/text/18/16):

> **The term “crime of violence” means (a) an offense that has as an element the use, attempted use, or threatened use of physical force against the person or prop­erty of another...**

As well as  California Penal Code Section 186.22(e) on gang participation:
> **Willfully promote, further, or assist felonious conduct by the gang members.**

Interestingly, other than the term "felonious", the language around gangs seems broad enough to encompass any group of people perpetuating violence - including government agencies.

## Is this intended to mean violent crimes or torts?

Yes both. The software is intended to be used for helping people philanthropically build things. The license generally permits free open source use amongst noncommercial philanthropic organizations. However, some noncommercial community and government groups organize around the intent of being violent, promoting or assisting violence. That's not what this software is for and we don't want to use the community's energy to support that. 

For example, we would not want CoMakery to be used by ICE or community organizations for the purpose of assisting ICE. Even though these are technically noncommercial, government or unincorporated groups under this license they would be promoting or assisting  "unwanted physical force". ICE and such community groups cannot use the software under this license. 

Also, throughout the world some protesters are engaged in coordinated destruction of property. Under the license the software cannot be used for that either.

## “physical force” (seems very broad if interpreted literally)

True! Surely we do not want to prohibit community farms from using the software because they are using shovels 😂 
That's why the term "unwelcome" was added.

Here's a tricky part. Some violence perpetuated by the government is legal and the intent is for the license to prohibit that use. Which makes some other methods of categorizing violence not broad enough. For example the language "assist felonious conduct by the gang members" relies on there being a felony... but in the case of violence perpetuated by ICE or the police, there is no felony.

Also, when sharing early drafts of the license people asked what the term "violence" meant. This suggested that a more direct description of "violence" as "unwanted physical force" might be more easily understood by both lawyers and non-lawyers reading the license.

## When is application of force to property unwelcome?
**like if I touch a building while passing on the sidewalk and the owner doesn’t actively welcome the light application of force but neither are they against it, would that be a violation of the license?**

The prohibited use clause is mainly so CoMakery has some recourse against the use of the software for violent purposes. The intent is for the phrase "unwanted physical force" to be interpreted in the context of evaluating what "nonviolent purposes" means in practice.

If you lightly touch a building, it's not explicitly unwanted nor is it physically forceful in the sense of violence. So it shouldn't trigger the prohibited purpose clause. In addition, the license isn't issued by the property owner and touching a building is below the threshold of what CoMakery wants to or practically could monitor.

However, there are definitely "light" uses of "unwanted physical force" that would be considered as violent such as some forms of sexual assault. With this in mind, specifying a measurement of force as a threshold of enforcement may not be practical.

## Conclusion

I'm very open to suggestions for making this definition clearer to both lawyers and non-lawyers. The clearer the language, the easier it is for philanthropic groups to freely use the software for positive outcomes without getting slowed down by the license - and that's the goal :)

**Comment by dazzaji** [comment]
Thank you for taking the time to write out this explanation. I find it very helpful.  

It sounds like the crux of it is “explicitly unwanted [and] physically forceful in the sense of violence”.  I think the term “explicitly unwanted“ is a more specific scope than “unwelcome” and the phrase “physically forceful in the sense of violence” narrows down the intended meaning to a more manageable set of interpretations.  

Can I suggest adding some commentary or an FAQ to the license to help people understand what you have in mind with this novel language?  

Cheers,

Daniel "Dazza" Greenwood, JD
CIVICS.com & Law.MIT.edu

**Comment by aquabu** [comment]
Thanks @dazzaji - I think "explicitly unwanted" is an improvement. I'm going to wait for a full round of feedback to come in before amending the license. 

Yes, creating an FAQ is a great idea. I think this thread is a good start. Thanks for bringing the Qs to help me articulate the As :)

**Comment by aquabu** [comment]
For further contemplation and for others who may have additional comments, this would change the Prohibited Purpose terms to:

> **You may not use the software to promote, further, or assist the use of explicitly unwelcome physical force in the sense of violence against people or property.**

or

> **You may not use the software to promote, further, or assist the use of explicitly unwelcome physical force against people or property in the sense of violence.**

**Comment by dazzaji** [comment]
I wonder if the term "unwelcome" works as well as "unconsented".  For example, a football tackle within the rules is also violent and unwelcome by the quarterback but it is also consensual.

**Comment by aquabu** [comment]
Good point @dazzaji . The license should permit use for sports. 

The modified phrase would be
> **You may not use the software to promote, further, or assist the use of unconsented physical force in the sense of violence against people or property.**

We would get a matrix that looks like this:

|  "Promote, further or assist"  | "unconsented physical force" | "in the sense of violence" | Permitted Use Of License? |
| ---  | --- | --- | --- |
| touching a building while passing on the sidewalk | yes | no | yes |
| boxing match uppercut | no | yes | yes |
| physical assault | yes | yes | no |
| sexual abuse | yes | yes, but the term "abuse" may clarify intent as applying to non-forceful cases | no |

Maybe "abuse" is a clearer term than "violence" in the case of people. Would it be clearer to separate out the people and property parts into something like:

> **You may not use the software to promote, further, or assist the use of unconsented physical force in the sense of abuse of people or destruction of property.**

**Comment by dazzaji** [comment]
This is a very helpful matrix!  I wonder if a phrase like "unlawful and/or unconsented" would cover cases like sexual abuse (and other situations) more clearly?

**Comment by aquabu** [comment]
Yes that could be clarifying. Possibly:
> **You may not use the software to promote, further, or assist the use of unlawful and/or unconsented physical force in the sense of abuse of people or destruction of property.**

I was also thinking about how to prohibit the instigation to self-harm or inducement of suicide. Self-harm is both consented and legal physical force. The instigation of it varies by jurisdiction:
https://www.loc.gov/law/foreign-news/article/brazil-new-law-criminalizes-instigation-to-self-harm/

More context on the issue from Instagram:
https://about.instagram.com/blog/announcements/supporting-and-protecting-vulnerable-people-on-instagram

**Comment by zippy** [comment]
Hi @aquabu.  The conversation with you and @JeanMRussell a couple weeks ago really got me thinking about violence/non-violence.  It seems more and more right to shift the ontology of violence/non-violence from a conceptual binary in the realm of physical force, to gradients in the dimensions of harm and consent.  

I know it may not make sense to try and expand this particular license out of the realm of physical force, but for the purpose of the dialog and potential future licenses, it seems clear that there are many types of non-physical harm that one might want to distinguish as un-permitted uses.

A mulit-dimensional spectra of harm and consent allows us to talk and think about all kinds things that all have the feel of "violence".  Also it matches my own experience that the more harm and greater the lack of consent the more "violent" an experience feels.  It means that we can distinguish many kinds of harm: physical, emotional, reputational, economic, political, etc.  At the same time we can distinguish the types of consent that are present for that particular situation.  There is overt consent (of the type that's written in contracts or spoken agreements), implicit consent (as given when you step into the boxing ring), there's "consent" under duress (which is is thus it's own interesting kind of "meta-violence"), and also there's the kind of fake "consent" that's built into explicit or systemically limited choice offerings, as in the "choice" of jobs that's available to you when you graduate from a poor under-funded inner-city school, or the "consent of the governed" to a list of candidates limited on a ballot.  These latter examples where it's clear that the system provides a small subset of choices to some people and not others, (which leads to the harm of poor living conditions, stress, disenfranchisement, etc) is a kind of systemic violence.

So, interestingly, such a license might have this simplified language:

> You may not use the software to promote, further, or assist the use of unconsented harm to people or property.

This addresses the case of touching a wall while walking past (not harm, (unless it is, i.e. in some imagined situation where touching a wall creates a harm of disrespect of a sacred wall)), and also addresses the case of arguing that the running of a doxing collective, or a social-media dis-information campaign, both of which create harm, to be non-permitted uses.  And it means that any discussion or litigation lands right where it should, in the questions of "what is harm?" and "what is consent?".   I also remove the "unlawful" because I imagine that one might want to allow civil disobedience, which is all about preventing possibly lawful unconsented harm by governments on people.   I also wonder if one shouldn't remove "property" from the list,  because the damage of a persons property is easily arguable as harm to that person.  It might be interesting to think about adding other beings that can't express consent but which can be harmed to the list, i.e. what is violence to the land, or to an ecosystem? But I think that might be scope creep!   

Thanks for the conversation and your work on embodying these concepts into the world!

**Comment by dazzaji** [comment]
Jumping in one more time - I like "You may not use the software to promote, further, or assist the use of unconsented harm to people or property." It's a big improvement.  But I have a bit of doubt on the enumerated actions, namely "promote, further, or assist".  If read very literally, it seems to omit the initial, causal conduct (ie the "carrying out" or "committing" etc) leading to the prohibited results, namely "unconsented harm to people or property".  To me, the word "furthering" strongly suggests you are a downstream actor, just extending or amplifying something that was previously separately in motion and already exists. And of course, when one enumerates things in legal rules then others (like those trying to wiggle out of violations) have another argument that the drafter must have meant the list as complete and exclusive and items not on the list should not later be interpreted to be included.  Adding more words like "this list is not exclusive and what is included are just examples" would be a step backward in the drafting of what should be a relatively simple rule that people can clearly understand and follow.  It would be better to cover all the things intended in the list to start with.  So I wonder if just adding the word "perpetrate" would eliminate doubt about what conduct breaches the license?  

The other remaining niggling doubt I have is the phrase "use of" in this formulation. I felt the phrase made more sense in the initial drafts but in this much tighter sentence, it feels out of place and more like an additional hurdle.  I wonder if the phrase "use of" at this point just creates another necessary link that might give people later something to argue over and get distracted about.  If the phrase were deleted at this point, would the rule actually become clearer and more direct, without losing any desirable meaning? 

So, altogether, adding the doing of the act (ie perpetrating the act) and removing the "use of" verbiage, it would read: 

> You may not use the software to perpetrate, promote, further, or assist unconsented harm to people or property. 

Given the more precise draft as it stands, I also agree it's a good call to remove "unlawful" because, as @zippy points out, the focus should be on identifying and enforceably ensuring consent and prohibiting the harm.

**Comment by zippy** [comment]
I will add a note here that [the Cryptographic Autonomy License](https://github.com/h-be/acorn-hc/blob/master/LICENSE.md) that we developed for Holochain, is also fundamentally about consent, i.e. that one may not remove the end-users ability to remove consent by taking their data and going elsewhere.  Another way of describing it is that it's about structurally empowering consent through the ability to fork not just code, but state which is fundamentally a necessary capacity for actual distributed systems.

**Comment by aquabu** [comment]
> @dazzaji : should be a relatively simple rule that people can clearly understand and follow

Yes, it is essential that people can identify what is a disallowed action. This is critical for adoption and for the software to be useful. For example philanthropies and academic institutions shouldn't be blocked by their legal department from using the software out of fear that they might trivially violate the terms. The license is meant to be noninvasive for typical use cases.

In keeping, there is intentional restraint in the license regarding ambiguous categories of things. This is because there is an "ambiguous harm" versus "usability" trade off to allow the license to be reliably and easily usable by generally good actors. 

The alternative is to evaluate each software user and issue them a revokable license after evaluating them. In my opinion, that creates both a huge administrative burden and too much uncertainty on behalf of the license recipients to be effective at scale. The license nonviolent clause is intended to be a harm reduction safety net rather than a legal tool for perfect control. Ultimately it's not the license issuer's role to weigh in on every gray area - that seems like overreach. The gray area may be better handled through things like contributor covenants, community culture and application design.

> @dazzaji :  I also agree it's a good call to remove "unlawful" because, as @zippy points out the focus should be on identifying and enforceably ensuring consent and prohibiting the harm.

Yes, for example government agencies all over the world use lawful violent action regularly. Coordinating lawful violence is not what the software is for. It is intentionally excluded in v1.0.

> @zippy : [in the Cryptographic Autonomy License] one may not remove the end-users ability to remove consent by taking their data and going elsewhere

Yes! Removing options is hidden coercion. Protecting consent is an amazing topic with important implications. 

It's fascinating how open source has been about freedom of code, and user data is the proprietary closed asset that is monetized. The Cryptographic Autonomy License broaches the topic nicely. I mean code is data... why is open source traditionally only about the computation part? I think the grammar is expanding now with Holochain, ethical source, strong copyleft, cryptographic contract enforcement and such. These changes will have vast implications. The trick will be to avoid tribalizing around possibility subsets such that we are unable to find the most effective solutions in this new territory.

On a very related note, I'm hosting an online SF Legal Hackers expert panel on August 17th, 2020 6:30pm Pacific to talk about Ethical Source, Strong Copy Left and Open Software Business Models:
https://www.meetup.com/SFLegalHackers/events/272330356/

**Comment by dazzaji** [comment]
That Legal Hackers event sounds amazing! What do you think of “You may not use the software to perpetrate, promote, further, or assist unconsented harm to people or property.“  Does that cover what you want it to cover?

**Comment by aquabu** [comment]
Thanks @dazzaji ! I think it does. I should review all the angles again before updating.

**Comment by aquabu** [comment]
@dazzaji & @zippy thanks again for great input. I just finalized and committed the proposed changes from @dazzaji LICENSE v1.1: https://github.com/CoMakery/comakery-server/commit/20ac1f15193aed3efa81e50110440c7b81a40f26
🎉 🎉 🌮 

Sorry this took so long. I have learned that I have a nearly irrational fear of changing LICENSE text in public repositories 🕷️ 😂

**Comment by dazzaji** [comment]
The prohibited purpose clause is truly remarkable. It is nearly impossible to articulate the ethic and principle of non-violence in an objectively enforceable way without inviting anomalous outcomes. By Jove I do believe you have done it with this clause:  “Prohibited Purpose — You may not use the software to perpetrate, promote, further, or assist unconsented harm to people or property.”

Daniel "Dazza" Greenwood, JD
CIVICS.com & Law.MIT.edu
