### ISSUE TITLE
Deploying to Heroku: not quite one-click...?

### ISSUE THREAD

**Issue by jslabovitz** [CoMakery/comakery-server#1697]
> If you want to deploy a new a new CoMakery Server on Heroku just press this button:

I was looking forward to a one-click install... but, well, not quite. Clicking that prompts me for a decent handful of apparently-required config variables. I'll admit I'm a bit rusty on modern Rails/cloud tech, but still I'm unsure exactly what other dependent services I need to get installed first, along with the specific answers to the following variables:

- APP_HOST, APP_NAME -- Do we need to have a DNS name to attach this to, or can we experiment with Heroku without?
- AWS_API_KEY, AWS_API_SECRET -- AWS I presume...
- CLOUDFRONT_HOST -- Is CloudFront really required?
- DISCORD_BOT_TOKEN, DISCORD_CLIENT_ID, DISCORD_CLIENT_SECRET -- For simple installs, could we do without Discord for now?
- ETHEREUM_EXPLORER_SITE -- I don't know what this is.
- GOOGLE_ANALYTICS, GOOGLE_TAG_MANAGER -- For privacy/security reasons, I do hope this is optional.
- INTERCOM_APP_ID -- ???
- NODE_MODULES_CACHE -- ???
- REFILE_S3_BUCKET, REFILE_S3_REGION -- related to AWS/S3 above? 
- SIDEKIQ_PASSWORD, SIDEKIQ_USERNAME -- ???
- SLACK_API_KEY, SLACK_API_SECRET -- as above in Discord: can this be optional?

I'm happy to work with you to come up with an install doc or video that helps folks like me set up the dependent services and related configuration.

**Comment by aquabu** [comment]
hi @jslabovitz 

> I was looking forward to a one-click install... but, well, not quite. 
Yes, install process getting easier would be good! There's still some devops involved. The values there are the services required to run CoMakery.com

Probably the best approach would be to make many of these either have a default or be optional parameters.

@Alexey1100 which of these do you think should:
* have to be required
* have a default value
* be disabled by default (with the option to add the parameter after setup)

The other thing is that we probably want to default to the white label setup on the one click deploy. The CoMakery landing page doesn't make sense as a default install.

**Comment by Alexey1100** [comment]
@jslabovitz thanks for trying it out!
Even if we set all env variables correctly, I think the button config haven't been updated for a while and the deployment might be broken atm.

**Comment by Alexey1100** [comment]
@aquabu I'll take a look on the variables and I think, yes, defaulting to white label mode makes more sense.
In this case we would need to create a white label mission with env-provided domain during initialisation, unless non-white label env variable set.

**Comment by marz-hunter** [comment]
hi, are there any more detailed steps for setting this up on my server? I tried using Docker but the ruby version doesn't support it, it's fixed by matching versions. but while running it looks like the server is not running and I don't know what the problem is, if anyone makes setup with more detailed steps I will be very grateful.

**Comment by aquabu** [comment]
hi @marz-hunter thanks for your interest. We are optimizing for Heroku easy deployment configuration using the app.json file. 

Since this issue was opened we've been gradually removing dependencies on non-heroku infrastructure to get to 1 click deployment. We are almost there but not quite. Notably we are moving away from any AWS requirements but the app.json temporarily requires some dummy values for AWS.

The project is under very active development right now, so there may be some issues from the acceptance branch. Once we stabilize the Heroku 1 click button we will tag that version as a release.

The docker instance is mostly for development rather than deployment currently.

**Comment by aquabu** [comment]
@marz-hunter also, if you find bugs or security holes please ping me. Seems like you are on the hackery side.

**Comment by aquabu** [comment]
Also @jslabovitz I was going to update you on the one click install once finished. We are pretty close. It took a bunch of work to simplify the Heroku deploy by changing services.

**Comment by marz-hunter** [comment]
hi @aquabu, thanks for the quick reply. but i want to set this up on my local server because heroku will cut costs for psql and it is a shame to use it for testing only, and i will be free enough to test on my own server, contact me again if there is a way to setup this on local server or my dm on twitter is in the bio if you have a test environment for https://www.comakery.com/doc/api/v1/index.html. thanks

**Comment by aquabu** [comment]
@jslabovitz the one click deploy to Heroku should work for you now. We factored out all dependencies on external services like Heroku and created default values. You will want to look through the environment variables to either configure on or after deployment.

@marz-hunter although this isn't the cheapest solution for spinning up a pen testing server with Docker it will allow one click deployment to Heroku. You can downgrade add ons like postgres to hobby tier to avoid expenses - I believe these add on fees are billed on a continuous basis rather than on launch for typical Heroku saas accounts (non-enterprise).
